<?php

/*
 * This file is part of the dupman/agent project.
 *
 * (c) 2022. dupman <info@dupman.cloud>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * Written by Temuri Takalandze <me@abgeo.dev>, February 2022
 */

/**
 * Implements hook_uninstall().
 */
function dupman_agent_uninstall() {
  $state = \Drupal::service('state');
  $state->delete('dupman_agent.token');
}
